# Generated by Django 3.2.5 on 2021-08-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_seller_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='categoty',
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.seller'),
        ),
    ]
