# Generated by Django 3.2.5 on 2021-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ads_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
